server:
  port: 8765
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${my.service.host}/eureka/
my:
  service:
    host: http://${eureka.instance.hostname}:8761/eureka/server