server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: git://10.252.19.98/
          search-paths: respo
          default-label: master
          username:
          password: