logging:
  config: classpath:config/logback-spring.xml

server:
  servlet:
    context-path: /produce/eureka
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  application:
    name: produce-eureka
