server:
  port: 9010
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: ${my.service.host}/eureka/
my:
  service:
    host: http://${eureka.instance.hostname}:9000/server/registry