server:
  port: 9020
eureka:
  instance:
    hostname: c-128
  client:
    service-url:
      defaultZone: ${my.service.host}/eureka/
my:
  service:
    host: http://${eureka.instance.hostname}:9000/eureka/server