logging:
  config: classpath:config/logback-spring.xml

server:
  servlet:
    context-path: /customer/ribbon
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  application:
    name: customer-ribbon
